/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dictionary.h"


void
add_prog_1(char *host, char* word, char* meaning)
{
	CLIENT *clnt;
	result  *result_1;
	insert_data  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

  strncpy(add_1_arg.word, word, strlen(word));
  add_1_arg.word[strlen(word)] = '\0';
  strncpy(add_1_arg.meaning, meaning, strlen(meaning));
  add_1_arg.meaning[strlen(meaning)] = '\0';

  result_1 = add_1(&add_1_arg, clnt);
  if (result_1 == (result *) NULL) {
    clnt_perror (clnt, "call failed");
  } else {
	printf("%s\n", result_1->data);
  }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
search_prog_1(char *host, char* word)
{
	CLIENT *clnt;
	result  *result_1;
	search_data  search_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SEARCH_PROG, SEARCH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    strncpy(search_1_arg.word, word, strlen(word));
    search_1_arg.word[strlen(word)] = '\0';

	result_1 = search_1(&search_1_arg, clnt);
	if (result_1 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
    	printf("%s\n", result_1->data);
  	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
delete_prog_1(char *host, char* word)
{
	CLIENT *clnt;
	result  *result_1;
	delete_data  delete_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DELETE_PROG, DELETE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    strncpy(delete_1_arg.word, word, strlen(word));
    delete_1_arg.word[strlen(word)] = '\0';

	result_1 = delete_1(&delete_1_arg, clnt);
	if (result_1 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
    	printf("%s\n", result_1->data);
  	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    while (1) {
      int choice = 0;
      char word[128] = {'\0'};
      char meaning[256] = {'\0'};

      printf("Please choose the option below.\n");
      printf("Entering other option will Exit.\n");
      printf("1. Enter new word.\n2. Search for word.\n3. Delete word.\n");
      scanf("%d", &choice);

      switch(choice) {
        case 1:
          printf("Enter word: ");
          scanf("%s", &word);
          printf("Enter meaning : ");
          scanf("%s", &meaning);
          add_prog_1 (host, word, meaning);
          break;
        case 2:
          printf("Enter the word to search: \n");
          scanf("%s", &word);
          search_prog_1 (host, word);
          break;
        case 3:
          printf("Enter the word to delete : \n");
          scanf("%s", &word);
          delete_prog_1 (host, word);
          break;
        default:
          printf("Wrong choice entered exiting program\n");
          exit(0);
          break;
      }
    }
exit (0);
}
